#!/usr/bin/env python3
"""
Build thesis/report comparison tables from an aggregated run CSV.

Usage
-----
python tools/make_comparison_table.py \
  --in results_summary.csv \
  --out-csv comparison_table.csv \
  --out-md comparison_table.md

Input
-----
CSV generated by tools/aggregate_results.py.

Output
------
1) A clean report-ready CSV table.
2) A Markdown table with the same columns.
"""

from __future__ import annotations

import argparse
import csv
import math
import statistics
import sys
from pathlib import Path
from typing import Dict, List, Tuple


OUTPUT_COLUMNS = [
    "Method",
    "Dataset",
    "Final Avg Acc",
    "Avg Forgetting",
    "Fu",
    "WorstDrop",
    "Au",
    "Retrain Time",
]

METRIC_COLUMNS = [
    ("final_avg_accuracy", "Final Avg Acc"),
    ("average_forgetting", "Avg Forgetting"),
    ("Fu", "Fu"),
    ("WorstDrop", "WorstDrop"),
    ("Au", "Au"),
    ("t_retrain", "Retrain Time"),
]


def parse_float(value: str):
    if value is None:
        return None
    value = str(value).strip()
    if value == "":
        return None
    try:
        number = float(value)
        if math.isnan(number):
            return None
        return number
    except ValueError:
        return None


def mean_std(values: List[float]) -> Tuple[float, float]:
    if not values:
        return (None, None)
    if len(values) == 1:
        return (values[0], None)
    return (statistics.mean(values), statistics.stdev(values))


def fmt_mean_std(values: List[float], decimals: int) -> str:
    mean, std = mean_std(values)
    if mean is None:
        return ""
    if std is None:
        return f"{mean:.{decimals}f}"
    return f"{mean:.{decimals}f} ± {std:.{decimals}f}"


def read_rows(path: Path):
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            return list(csv.DictReader(handle))
    except FileNotFoundError:
        print(f"[ERROR] Input CSV not found: {path}", file=sys.stderr)
        return None
    except OSError as exc:
        print(f"[ERROR] Failed to read CSV: {path} ({exc})", file=sys.stderr)
        return None


def build_table(rows: List[Dict[str, str]], decimals: int):
    grouped: Dict[Tuple[str, str], List[Dict[str, str]]] = {}
    for row in rows:
        dataset = (row.get("dataset") or "").strip()
        method = (row.get("method") or "").strip()
        key = (dataset, method)
        grouped.setdefault(key, []).append(row)

    table = []
    for dataset, method in sorted(grouped.keys(), key=lambda x: (x[0], x[1])):
        group_rows = grouped[(dataset, method)]
        out_row = {
            "Method": method,
            "Dataset": dataset,
        }
        for in_col, out_col in METRIC_COLUMNS:
            values = []
            for row in group_rows:
                value = parse_float(row.get(in_col, ""))
                if value is not None:
                    values.append(value)
            out_row[out_col] = fmt_mean_std(values, decimals)
        table.append(out_row)
    return table


def write_csv(path: Path, rows: List[Dict[str, str]]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in OUTPUT_COLUMNS})


def write_markdown(path: Path, rows: List[Dict[str, str]]):
    path.parent.mkdir(parents=True, exist_ok=True)
    header = "| " + " | ".join(OUTPUT_COLUMNS) + " |"
    sep = "| " + " | ".join(["---"] * len(OUTPUT_COLUMNS)) + " |"
    lines = [header, sep]
    for row in rows:
        line = "| " + " | ".join(str(row.get(col, "")) for col in OUTPUT_COLUMNS) + " |"
        lines.append(line)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args():
    parser = argparse.ArgumentParser(description="Create report comparison tables from aggregated run CSV.")
    parser.add_argument("--in", dest="input_csv", type=Path, required=True, help="Input aggregated CSV path.")
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=Path("comparison_table.csv"),
        help="Output CSV report table path.",
    )
    parser.add_argument(
        "--out-md",
        type=Path,
        default=Path("comparison_table.md"),
        help="Output Markdown report table path.",
    )
    parser.add_argument("--decimals", type=int, default=4, help="Decimal precision for reported metrics.")
    return parser.parse_args()


def main():
    args = parse_args()
    rows = read_rows(args.input_csv)
    if rows is None:
        return 1

    table = build_table(rows, args.decimals)
    write_csv(args.out_csv, table)
    write_markdown(args.out_md, table)

    print(f"[INFO] Wrote CSV comparison table: {args.out_csv}")
    print(f"[INFO] Wrote Markdown comparison table: {args.out_md}")
    print(f"[INFO] Groups summarized: {len(table)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
