#!/usr/bin/env python3
"""
Build thesis/report ablation tables from an aggregated run CSV.

Usage
-----
python tools/make_ablation_table.py \
  --in results_summary.csv \
  --out-csv ablation_table.csv \
  --out-md ablation_table.md

Input
-----
CSV generated by tools/aggregate_results.py.

Output
------
1) A clean report-ready CSV table.
2) A Markdown table with the same columns.
"""

from __future__ import annotations

import argparse
import csv
import math
import statistics
import sys
from pathlib import Path
from typing import Dict, List, Tuple


BASE_OUTPUT_COLUMNS = [
    "Dataset",
    "Method",
    "Protect Ratio",
    "Lambda Protect",
    "Retrain Steps",
    "Epochs",
    "Final Avg Acc",
    "Avg Forgetting",
    "Fu",
    "WorstDrop",
    "Au",
    "Retrain Time",
]

ADAPTER_OUTPUT_COLUMNS = [
    "Dataset",
    "Method",
    "Adapter Bottleneck",
    "Train Classifier",
    "Adapter Location",
    "Final Avg Acc",
    "Avg Forgetting",
    "Fu",
    "WorstDrop",
    "Au",
    "Retrain Time",
]

BASE_GROUP_COLUMNS = [
    ("dataset", "Dataset"),
    ("method", "Method"),
    ("protect_ratio", "Protect Ratio"),
    ("lambda_protect", "Lambda Protect"),
    ("retrain_steps", "Retrain Steps"),
    ("n_epochs", "Epochs"),
]

ADAPTER_GROUP_COLUMNS = [
    ("dataset", "Dataset"),
    ("method", "Method"),
    ("adapter_bottleneck", "Adapter Bottleneck"),
    ("adapter_train_classifier", "Train Classifier"),
    ("adapter_location", "Adapter Location"),
]

METRIC_COLUMNS = [
    ("final_avg_accuracy", "Final Avg Acc"),
    ("average_forgetting", "Avg Forgetting"),
    ("Fu", "Fu"),
    ("WorstDrop", "WorstDrop"),
    ("Au", "Au"),
    ("t_retrain", "Retrain Time"),
]


def parse_float(value: str):
    if value is None:
        return None
    value = str(value).strip()
    if value == "":
        return None
    try:
        number = float(value)
        if math.isnan(number):
            return None
        return number
    except ValueError:
        return None


def normalize_group_value(value: str) -> str:
    if value is None:
        return ""
    return str(value).strip()


def sort_group_value(value: str):
    if value == "":
        return (1, "")
    number = parse_float(value)
    if number is not None:
        return (0, number)
    return (0, value)


def mean_std(values: List[float]) -> Tuple[float, float]:
    if not values:
        return (None, None)
    if len(values) == 1:
        return (values[0], None)
    return (statistics.mean(values), statistics.stdev(values))


def fmt_mean_std(values: List[float], decimals: int) -> str:
    mean, std = mean_std(values)
    if mean is None:
        return ""
    if std is None:
        return f"{mean:.{decimals}f}"
    return f"{mean:.{decimals}f} ± {std:.{decimals}f}"


def read_rows(path: Path):
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            return list(reader), list(reader.fieldnames or [])
    except FileNotFoundError:
        print(f"[ERROR] Input CSV not found: {path}", file=sys.stderr)
        return None
    except OSError as exc:
        print(f"[ERROR] Failed to read CSV: {path} ({exc})", file=sys.stderr)
        return None


def has_adapter_ablation(rows: List[Dict[str, str]], fieldnames: List[str]) -> bool:
    if "adapter_bottleneck" not in fieldnames:
        return False
    for row in rows:
        if any(
            normalize_group_value(row.get(column, "")) != ""
            for column in ("adapter_bottleneck", "adapter_train_classifier", "adapter_location")
        ):
            return True
    return False


def build_table(rows: List[Dict[str, str]], decimals: int, group_columns):
    grouped: Dict[Tuple[str, ...], List[Dict[str, str]]] = {}
    for row in rows:
        key = tuple(normalize_group_value(row.get(in_col, "")) for in_col, _ in group_columns)
        grouped.setdefault(key, []).append(row)

    sorted_keys = sorted(
        grouped.keys(),
        key=lambda key: tuple(sort_group_value(value) for value in key),
    )

    table = []
    for key in sorted_keys:
        group_rows = grouped[key]
        out_row = {}
        for idx, (_, out_col) in enumerate(group_columns):
            out_row[out_col] = key[idx]
        for in_col, out_col in METRIC_COLUMNS:
            values = []
            for row in group_rows:
                value = parse_float(row.get(in_col, ""))
                if value is not None:
                    values.append(value)
            out_row[out_col] = fmt_mean_std(values, decimals)
        table.append(out_row)
    return table


def write_csv(path: Path, rows: List[Dict[str, str]], output_columns: List[str]):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=output_columns)
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in output_columns})


def write_markdown(path: Path, rows: List[Dict[str, str]], output_columns: List[str]):
    path.parent.mkdir(parents=True, exist_ok=True)
    header = "| " + " | ".join(output_columns) + " |"
    sep = "| " + " | ".join(["---"] * len(output_columns)) + " |"
    lines = [header, sep]
    for row in rows:
        line = "| " + " | ".join(str(row.get(col, "")) for col in output_columns) + " |"
        lines.append(line)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args():
    parser = argparse.ArgumentParser(description="Create ablation tables from aggregated run CSV.")
    parser.add_argument("--in", dest="input_csv", type=Path, required=True, help="Input aggregated CSV path.")
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=Path("ablation_table.csv"),
        help="Output CSV ablation table path.",
    )
    parser.add_argument(
        "--out-md",
        type=Path,
        default=Path("ablation_table.md"),
        help="Output Markdown ablation table path.",
    )
    parser.add_argument("--decimals", type=int, default=4, help="Decimal precision for reported metrics.")
    return parser.parse_args()


def main():
    args = parse_args()
    loaded = read_rows(args.input_csv)
    if loaded is None:
        return 1
    rows, fieldnames = loaded

    use_adapter_schema = has_adapter_ablation(rows, fieldnames)
    group_columns = ADAPTER_GROUP_COLUMNS if use_adapter_schema else BASE_GROUP_COLUMNS
    output_columns = ADAPTER_OUTPUT_COLUMNS if use_adapter_schema else BASE_OUTPUT_COLUMNS

    table = build_table(rows, args.decimals, group_columns)
    write_csv(args.out_csv, table, output_columns)
    write_markdown(args.out_md, table, output_columns)

    print(f"[INFO] Wrote CSV ablation table: {args.out_csv}")
    print(f"[INFO] Wrote Markdown ablation table: {args.out_md}")
    print(f"[INFO] Groups summarized: {len(table)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
